name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ignore-main-{0}', github.run_id) || format('{0}-{1}', github.workflow, github.ref_name) }}
  cancel-in-progress: true

jobs:
  integration-test:
    uses: ./.github/workflows/integration-test.yaml
    with:
      charm-file-name: "vault-k8s_ubuntu-22.04-amd64.charm"
      enable-metallb: true
